# Right now, we're using Postgres on the host, so first create the postgres user (mastodon).
# Be sure to redirect https://example.com/.well-known/webfinger to https://mastodon.example.com/.well-known/webfinger
# and the same for /.well-known/host-meta.
# TODO: cronjobs for cleanups as described in https://docs.joinmastodon.org/admin/setup/

- name: Create Postgres user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ mastodon_db_user }}"
    password: "{{ mastodon_db_password }}"

- name: Create database
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ mastodon_db_name }}"
    owner: "{{ mastodon_db_user }}"

- name: Create Mastodon data directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  loop:
    - /data/mastodon
    - /data/mastodon/files-proxy

- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml
    dest: /data/mastodon/docker-compose.yml
    mode: 0644

- name: Copy config
  ansible.builtin.template:
    src: config
    dest: /data/mastodon/config
    mode: 0640
  register: _config

- name: Copy files proxy configuration
  ansible.builtin.template:
    src: nginx_files_proxy.conf
    dest: /data/mastodon/files-proxy/nginx.conf
    mode: 0644
  register: _files_proxy_config

- name: Create Docker network
  community.docker.docker_network:
    name: "{{ mastodon_network }}"
    state: present

- name: Start Mastodon stack
  community.docker.docker_compose_v2:
    project_src: /data/mastodon
    restarted: "{{ (_config is defined and _config.changed) or (_files_proxy_config is defined and _files_proxy_config.changed) }}"
  # notify:
  #   - Migrate Mastodon database
